# Generated by Django 5.2.4 on 2025-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.PositiveSmallIntegerField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('review_content', models.TextField()),
                ('date', models.DateField()),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(choices=[('trustpilot', 'Trustpilot'), ('traders_union', 'Traders Union'), ('review_io', 'Review.io'), ('brokersview', 'Brokersview'), ('forex_peace_army', 'Forex Peace Army')], max_length=50)),
            ],
        ),
    ]
